### ISSUE TITLE
Long_Plugin_Output on passive checks ignored

### ISSUE THREAD

**Issue by Mike-Sbg** [NagiosEnterprises/nagioscore#141]
When a check is actively triggered, everything works fine, but if the result is putted in via cmd-file (as a passive check result) the long output is putted into the plugin_output (long_plugin_output stays empty)

You can reproduce this bug, with this simple command.

`echo -e "[$(date +%s)] PROCESS_SERVICE_CHECK_RESULT;SERVERNAME;Test;0;Test new entry \n should be long output" >> /var/lib/nagios/nagios.cmd​`

**Comment by box293** [comment]
When I watch the nagios log, I see the following logged when I use your command:
```
[1468803451] External command error: Malformed command
```
However if I remove the "-e" from your echo command it appears to work correctly:

```
echo "[$(date +%s)] PROCESS_SERVICE_CHECK_RESULT;SERVERNAME;Test;0;Test new entry \n should be long output" >> /var/lib/nagios/nagios.cmd
```

**Comment by Mike-Sbg** [comment]
I'll try this, but the "\n" doesn't seperate the different command lines ... simply everything is putted in the (short) plugin-output including the "\n" ...

**Comment by Mike-Sbg** [comment]
Sorry, but when I remove the "-e" nothing changes, everything will be put in the (short) plugin-output even the "\n" ... 

I know there are different echo commands, I use CentOS 7 with bash as shell

**Comment by box293** [comment]
What version of Nagios Core are you using?

I don't see that behaviour on my test systems here (Core 4.1.1).

If I use the JSON API I can look at the object once the the result has been submitted and I see the following:
```
"plugin_output": "Test new entry 8830",
"long_plugin_output": " should be long output",
```
Here's the command:
```
echo "[$(date +%s)] PROCESS_SERVICE_CHECK_RESULT;localhost;HTTP;0;Test new entry $RANDOM\n should be long output" >> /usr/local/nagios/var/rw/nagios.cmd 
```
Here's what's logged in nagios.log:
```
[1468824116] EXTERNAL COMMAND: PROCESS_SERVICE_CHECK_RESULT;localhost;HTTP;0;Test new entry 8830\n should be long output
```
Here's the json query:
```
curl --user nagiosadmin:nagiosadminpassword 'http://core-010/nagios/cgi-bin/statusjson.cgi?query=service&hostname=localhost&servicedescription=HTTP'
```
Here's the output:
```
{
  "format_version": 0,
  "result": {
    "query_time": 1468824118000,
    "cgi": "statusjson.cgi",
    "user": "nagiosadmin",
    "query": "service",
    "query_status": "released",
    "program_start": 1468823729000,
    "last_data_update": 1468824108000,
    "type_code": 0,
    "type_text": "Success",
    "message": ""
  },
  "data": {
    "service": {
      "host_name": "localhost",
      "description": "HTTP",
      "host_name": "localhost",
      "description": "HTTP",
      "plugin_output": "Test new entry 8830",
      "long_plugin_output": " should be long output",
      "perf_data": "",
      "max_attempts": 4,
      "current_attempt": 1,
      "status": 2,
      "last_update": 1468824108000,
      "has_been_checked": true,
      "should_be_scheduled": true,
      "last_check": 1468824099000,
      "check_options": 0,
      "check_type": 1,
      "checks_enabled": true,
      "last_state_change": 1468824099000,
      "last_hard_state_change": 1468823749000,
      "last_hard_state": 0,
      "last_time_ok": 1468823952000,
      "last_time_warning": 1468824099000,
      "last_time_unknown": 0,
      "last_time_critical": 1440051849000,
      "state_type": 1,
      "last_notification": 0,
      "next_notification": 0,
      "next_check": 1468824132000,
      "no_more_notifications": false,
      "notifications_enabled": false,
      "problem_has_been_acknowledged": false,
      "acknowledgement_type": 0,
      "current_notification_number": 0,
      "accept_passive_checks": true,
      "event_handler_enabled": true,
      "flap_detection_enabled": true,
      "is_flapping": false,
      "percent_state_change": 6.12,
      "latency": 0.92,
      "execution_time": 0.00,
      "scheduled_downtime_depth": 0,
      "process_performance_data": true,
      "obsess": true
    }
  }
}
```

Here's a link to some info about the JSON API:
https://labs.nagios.com/2014/06/19/exploring-the-new-json-cgis-in-nagios-core-4-0-7-part-1/

**Comment by Mike-Sbg** [comment]
I'm testing it on Nagios 4.0.8 on an CentOS 7

**Comment by Mike-Sbg** [comment]
I posted the request also on the naemo Github-Issue-Page and I got an really interestigen answer:

It was called a bug of the processing of the cmd-file. When I post it to the "query handler" it is parsed correctly ... I don't know if this helps

**Comment by box293** [comment]
Can you upgrade to 4.1.1 and see if the problem still exists.

I ran up a test machine of CentOS 7 and installed Core 4.0.8 and experienced the issue, status.dat was not being updated.

I then ran up a test machine of CentOS 7 and installed Core 4.1.1 and the problem did not occur, status.dat was being updated. 

I did experience that the json query was not showing the correct data however I know there are some fixes in the next release (4.1.2) that resolve some json issues.

**Comment by Mike-Sbg** [comment]
Thank you for you investigation ... but I had many troubles with 4.0.8 because it is rather unstable (Sigterm was caught) ... so I decided to try naemon 1.0.5, which is running on my development system. It works really stable and rpms for the centos 7 are provided, which makes it much easier to deploy it. 

So I'm really not sure what to do ... because my company policies engage me to avoid self compiling for productional-use ...

But if you tell me the problem was fixed in 4.1.1, I hope that one the one hand there will be a rpm -package for centos 7 or the naemon team will even fix it ...

Thank you very much

**Comment by box293** [comment]
We only provide support for Nagios Core.

An RPM of Nagios Core may be available one day, but right now that is not the case.

Compiling the latest version of Nagios Core is currently the only way you will be able to get the latest bug fixes and improvements.

If you have stability issues with Nagios Core we encourage you to head over to the Nagios Support forum and we will endeavour to get to the bottom of it. https://support.nagios.com/forum

Core 4.0.8 has been superseded by 4.1.1 and should be used for any future testing.

**Comment by Mike-Sbg** [comment]
Thank you for the status information ... I'll try out the version 4.1.1 as soon as possible.

**Comment by jfrickson** [comment]
No further info from @Mike-Sbg. Assuming this is a 4.0.8 issue that has been resolved in 4.1.x. Closing.

**Comment by Mike-Sbg** [comment]
Sorry ... I was on holiday, so I could not test it ... but today I installed Version 4.2.1 of Nagios, and to me it seems that the error still exists:

Status.dat on Nagios Version 3:

> plugin_output=Geladene Plugins: fastestmirror, presto, rhnplugin, security
> long_plugin_output=This system is receiving updates from RHN Classic or Red Hat Satellite.\nLoading mirror speeds from cached hostfile;

Status Output on Nagios 4:

> plugin_output=Geladene Plugins: fastestmirror, presto, rhnplugin, security\nThis system is receiving updates from RHN Classic or Red Hat Satellite.\nLoading mirror speeds from cached hostfile:
> long_plugin_output=

What further information, can I provide for helping to debug this problem?

**Comment by Mike-Sbg** [comment]
I finally found out was the problem is ... 

To separate the short from the long plugin output you can use the "\n" <- newline

This is imported via nsca to the nagios-server. The Nagios-Server can handle it without problem, but when it exports it again (via ocsp) the output is modified to "\\n" <- it disables the first Backslash ... when I transmit it to the Nagios 4 ... everything will be put in the short-plugin output.

The solution which works fine for me, is that I parse the ocsp-string to remove the second backslash ... then everything works fine ... 

So the problem is resolved from my point of view.

Finally: I like your work at Nagios!!!

**Comment by box293** [comment]
Great, thanks for posting your solution here.

**Comment by jfrickson** [comment]
Closing per original posters' request.
