### ISSUE TITLE
execvp seems truncated on 4.4.0

### ISSUE THREAD

**Issue by JasonRivers** [NagiosEnterprises/nagioscore#538]
Upgrading to 4.4.0 causes most of my services to error.

Snippet of Nagios Log after the upgrade:

> Successfully launched command file worker with pid 37
> nagios: Successfully launched command file worker with pid 37
> nagios: SERVICE ALERT: Wiki-Server;ICMPv4;CRITICAL;SOFT;1;(No output on stdout) stderr: execvp(/opt/nagios/libexec/ch, ...) failed. errno is 2: No such file or directory
> postfix/master[16]: daemon started -- version 3.1.0, configuration /etc/postfix
> nagios: SERVICE ALERT: Pippin;ICMPv4;UNKNOWN;SOFT;1;Usage:
> nagios: SERVICE ALERT: MailServer;POP3-IPv4;CRITICAL;SOFT;1;POP CRITICAL - Invalid hostname, address or socket: ma
> nagios: HOST ALERT: VOIP0;DOWN;SOFT;1;<wrta> was not set
> nagios: HOST ALERT: Nas02;DOWN;SOFT;1;check_ping: %s: Warning threshold must be integer or percentage!
> nagios: SERVICE ALERT: docker-build;ICMPv6;CRITICAL;SOFT;1;(No output on stdout) stderr: execvp(/opt/n, ...) failed. errno is 2: No such file or directory
> nagios: SERVICE ALERT: DyaPi01;ICMPv6;UNKNOWN;SOFT;1;<wrta> was not set
> nagios: HOST ALERT: DyaPi01;DOWN;SOFT;1;check_ping: %s: Warning threshold must be integer or percentage!
> nagios: SERVICE ALERT: DyaPi04;ICMPv4;UNKNOWN;SOFT;1;Usage:
> nagios: HOST ALERT: BitDefender;DOWN;SOFT;1;(No output on stdout) stderr: execvp(/opt/nagios/libexec/check_, ...) failed. errno is 2: No such file or directory
> nagios: HOST ALERT: DyaPi04;DOWN;SOFT;1;check_ping: %s: Warning threshold must be integer or percentage!
> nagios: SERVICE ALERT: BitDefender;ICMPv4;UNKNOWN;HARD;1;<wrta> was not set
> nagios: SERVICE ALERT: ESXi205;ICMPv4;CRITICAL;SOFT;1;CRITICAL - Plugin timed out
> nagios: SERVICE ALERT: Backup;ICMPv4;UNKNOWN;SOFT;1;<crta> was not set
> nagios: SERVICE ALERT: DyaPi06;ICMPv4;UNKNOWN;SOFT;1;Usage:
> nagios: SERVICE ALERT: Backup;Disk-Boot;CRITICAL;SOFT;1;(No output on stdout) stderr: /bin/sh: 1: Syntax error: Unterminated quoted string

All of these services were OK with 4.3.4, it looks like all of the calls for execvp have a truncated argument for the check.

Output of nagios -v

> Nagios Core 4.4.0
> Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
> Copyright (c) 1999-2009 Ethan Galstad
> Last Modified: 2018-06-19
> License: GPL
> 
> Website: https://www.nagios.org
> Reading configuration data...
>    Read main config file okay...
>    Read object config files okay...
> 
> Running pre-flight check on configuration data...
> 
> Checking objects...
> 	Checked 1057 services.
> 	Checked 109 hosts.
> 	Checked 36 host groups.
> 	Checked 0 service groups.
> 	Checked 5 contacts.
> 	Checked 6 contact groups.
> 	Checked 27 commands.
> 	Checked 2 time periods.
> 	Checked 0 host escalations.
> 	Checked 0 service escalations.
> Checking for circular paths...
> 	Checked 109 hosts
> 	Checked 0 service dependencies
> 	Checked 0 host dependencies
> 	Checked 2 timeperiods
> Checking global event handlers...
> Checking obsessive compulsive processor commands...
> Checking misc settings...
> 
> Total Warnings: 0
> Total Errors:   0
> 
> Things look okay - No serious problems were detected during the pre-flight check

Both 4.3.4 and 4.4.0 are using containers:
jasonrivers/nagios:4.3.4
jasonrivers/nagios:4.4.0

**Comment by sshmanko** [comment]
we are having exactly the same issue after upgrade, running on Centos 6 (kernel 4.9.93), compiled from source.

**Comment by hedenface** [comment]
What is the output of `ulimit -a`?

**Comment by hedenface** [comment]
Also, If I create a testing branch - would either of you be willing to test it?

**Comment by hedenface** [comment]
The only thing that changed in the `runcmd_open` function was a bit of cleanup. ***But*** I did update some compiler attributes for that function in the header file.

**Comment by sshmanko** [comment]
ulimit -a
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30467
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 30467
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
I can easily test from testing branch

**Comment by hedenface** [comment]
Can you give me some insight into how you performed the upgrade? Exact commands you executed?

**Comment by hedenface** [comment]
Okay - give me a few moments and I'll have the branch up.

**Comment by hedenface** [comment]
Meanwhile, I just did an upgrade from 4.3.4 to 4.4.0, and am not seeing these errors. I've tested this on many systems in the weeks leading up to the release, and not once saw that. What compiler did you use?

**Comment by hedenface** [comment]
Here is the branch with runcmd related things reverted:

https://github.com/NagiosEnterprises/nagioscore/tree/runcmd-revert

**Comment by JasonRivers** [comment]
Running on GCC 5.4.0 on Ubuntu 16.04 (all the build info that I use is in the Dockerfile linked above)

**Comment by hedenface** [comment]
That is a very nice Dockerfile. Okay - I'll attempt to replicate using Ubu 16, and if I can't I'll run the container. Please post back any information you have on the branch I pushed and if that fixes the issue in the meantime.

**Comment by JasonRivers** [comment]
I'm still having the same issue,

It's worth noting that the "default" config works OK.

You can run the container if you have a system with docker running, the container is here (built with the runcmd-revert branch): https://hub.docker.com/r/jasonrivers/nagios/ use the tag 4.4.0 (docker run jasonrivers.nagios:4.4.0) As there's 500K+ downloads of the image, I'm keeping "latest" on 4.3.4 until we can get 4.4.0 to work ;-)

I can send over the config if you have an email address I can use (I don't wish to put those in the public for obvious reasons)

**Comment by JasonRivers** [comment]
Within the container, I am keeping the sources in /tmp/nagioscore and confirmed that it is using the  correct branch:
```
root@e95fc1370f0f:/tmp/nagioscore# git branch
* runcmd-revert
```

**Comment by hedenface** [comment]
I'm able to replicate.

**Comment by hedenface** [comment]
Wait. Mine is just missing the plugins. But it's the same error as yours.

```
execvp(/usr/local/nagios/libexec/check_ping, ...) failed. errno is 2: No such file or directory
```

**Comment by hedenface** [comment]
Send me your configs at bheden@nagios.com

**Comment by hedenface** [comment]
And can you verify if the plugins actually exist in the places that Nagios is expecting them?

**Comment by sshmanko** [comment]
we get similar errors for NRPE checks as well, so it is not just files (files are there):

```
UNKNOWN;SOFT;1;NRPE: Command 'check' not defined
UNKNOWN;SOFT;1;NRPE: Command 'check_' not defined
UNKNOWN;HARD;2;NRPE: Command 'ch' not defined
```

**Comment by hedenface** [comment]
@sshmanko Are you using that Dockerfile, by chance?

**Comment by sshmanko** [comment]
no, separate VM, binary compiled from source

**Comment by hedenface** [comment]
Okay. Well this is pretty weird, I think then. What is the operating system/arch you're experiencing the issues on @sshmanko? Can you send me your configuration files? bheden@nagios.com

**Comment by JasonRivers** [comment]
Configs are sent, with redacted passwords, The checks are indeed in place, resources.cfg sets $USER1$ to be /opt/nagios/libexec which is where the container puts them.

**Comment by sshmanko** [comment]
Centos 6 (Amazon Linux ami)
4.9.93-41.60.amzn1.x86_64 #1 SMP Fri Apr 13 21:58:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I can't send my configuration, we have ~1,5k hosts and 4k services

Installation procedure is:
./configure
make all
make install

**Comment by hedenface** [comment]
@JasonRivers I have not yet received an email.

**Comment by JasonRivers** [comment]
@hedenface just resent from my office account as something is dicking about 

> status=deferred` (host mx.fusemail.net[72.35.23.4] said: 451 please retry later (gl) (in reply to RCPT TO command))

**Comment by JasonRivers** [comment]
@sshmanko just to update:

I have been email @hedenface with configs and debug logs, the latest thinking from him is:

> It looks like the config parser broke.

Hopefully it will be sorted soon!

**Comment by hedenface** [comment]
So running the test manually indicates that its just a permissions issue apparently:

```
root@46a5a1e2066d:/tmp/nagioscore/t# prove 900-configparsing.t 
900-configparsing.t .. 1/2 
#   Failed test 'Nagios validation failed:
# 
# Nagios Core 4.4.0
# Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
# Copyright (c) 1999-2009 Ethan Galstad
# Last Modified: 2018-06-19
# License: GPL
# 
# Website: https://www.nagios.org
# Reading configuration data...
#    Read main config file okay...
#    Read object config files okay...
# 
# Running pre-flight check on configuration data...
# 
# Checking objects...
# 	Checked 5 services.
# 	Checked 3 hosts.
# 	Checked 1 host groups.
# 	Checked 1 service groups.
# 	Checked 2 contacts.
# 	Checked 2 contact groups.
# 	Checked 5 commands.
# 	Checked 1 time periods.
# 	Checked 0 host escalations.
# 	Checked 4 service escalations.
# Checking for circular paths...
# 	Checked 3 hosts
# 	Checked 1 service dependencies
# 	Checked 0 host dependencies
# 	Checked 1 timeperiods
# Checking global event handlers...
# Checking obsessive compulsive processor commands...
# Checking misc settings...
# 	Error: Unable to write to check_result_path ('/tmp/nagioscore/t/var/spool/checkresults') - Permission denied
# 
# Total Warnings: 0
# Total Errors:   1
# 
# ***> One or more problems was encountered while running the pre-flight check...
# 
#      Check your configuration file(s) to ensure that they contain valid
#      directives and data definitions.  If you are upgrading from a previous
#      version of Nagios, you should be aware that some variables/definitions
#      may have been removed or modified in this version.  Make sure to read
#      the HTML documentation regarding the config files, as well as the
#      'Whats New' section to find out what has changed.
# 
# '
#   at 900-configparsing.t line 23.
Cannot create precached objects file at 900-configparsing.t line 26.
# Looks like you planned 2 tests but ran 1.
# Looks like you failed 1 test of 1 run.
# Looks like your test exited with 1 just after 1.
900-configparsing.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 2/2 subtests 

Test Summary Report
-------------------
900-configparsing.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 2 tests but ran 1.
```

**Comment by hedenface** [comment]
```
root@46a5a1e2066d:/tmp/nagioscore/t# chmod -R 777 var
root@46a5a1e2066d:/tmp/nagioscore/t# prove 900-configparsing.t 
900-configparsing.t .. ok   
All tests successful.
Files=1, Tests=2,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.05 CPU)
Result: PASS
root@46a5a1e2066d:/tmp/nagioscore/t# 
```

**Comment by JasonRivers** [comment]
I assume this is because nagios does runs a change UID when running as root (which is what we're running as in the container).

Bummer!

**Comment by hedenface** [comment]
Also, I forgot the `--enable-debugging --enable-coverage` flags for ./configure so it never would have passed for you.

Now that I reconfigured and changed perms `make test` is successful.

I'm going to transplant the configs now and see if I can replicate.

**Comment by hedenface** [comment]
Good news!

I have replicated the system on a non-container.

**Comment by hedenface** [comment]
Set 

```
enable_environment_macros=0
```

And restart Core and tell me if you're still having the issue, please.

**Comment by hedenface** [comment]
Verified the fix with https://github.com/NagiosEnterprises/nagioscore/commit/11901bc17f897075d3b111c23335a2ca8c1b8229

I would like some more eyes on it while I'm testing though, if possible.

**Comment by sshmanko** [comment]
@hedenface setting enable_environment_macros=0 fixed the issue for me, thanks a lot!

**Comment by hedenface** [comment]
Nonononononooooooo!

That was only part of the problem - the actual fix is in the commit listed above. The environment_macros thing is just a trigger - there are still many other problems. Can you test with the commit - even with enable_environment_macros=1 ?

**Comment by hedenface** [comment]
Closing this, as I've confirmed the fix on several instances where I have since been able to replicate.

**Comment by sshmanko** [comment]
confirm fixed on maint branch (still getting return code 22 though on some checks)

**Comment by JasonRivers** [comment]
Also confirmed working on branch maint, on the container. Thanks!
